### ISSUE TITLE
js style? 4 space indent vs. 2 space indent etc. following Agoric / airbnb norms

### ISSUE THREAD

**Issue by dckc** [ski/umqhele#1]
when I updated the access token in `lib/capt.js`, the whole file changed when I hit save... cuz I have lint-on-save enabled, combined with 2 space indent per Agoric js norms (derived from airbnb)

ref https://github.com/Agoric/agoric-sdk/blob/master/packages/captp/.eslintrc.js

**Comment by ski** [comment]
I have added the above linting configuration to the project with the agoric configuration. Also changed my settings to two space instead of tab.
